---
name: Build GO CLI

on:                          # yamllint disable-line rule:truthy
  schedule:
    - cron: '34 08 * * 6'

  workflow_dispatch:

  push:
    branches-ignore:
      - 'update/**'
      - 'dependabot/**'

jobs:

  "macOS":
    runs-on:
      - self-hosted

    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: macOS GO Build
        run: $HOME/github/bin/build_go_macos.sh

  "linux":
    runs-on:
      - self-hosted

    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Linux GO Build
        run: $HOME/github/bin/build_go_linux.sh
