name: macOS GO build


on:
  schedule:
      - cron: '34 08 * * 6'   # Every Saturday
  workflow_dispatch:
  push:

jobs:

  Build_and_AppCast_for_macOS:
    runs-on:
      - self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.20'

    - name: macOS GO Build
      run: $HOME/github/bin/build_go_macos.sh


