---
name: macOS GO build

on:                          # yamllint disable-line rule:truthy
  schedule:
    - cron: '34 08 * * 6'
  workflow_dispatch:
  push:

jobs:

  Build_and_AppCast_for_macOS:
    runs-on:
      - self-hosted

    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: macOS GO Build
        run: $HOME/github/bin/build_go_macos.sh
