name: macOS build

env:
  NAME: 'header_check'

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: 
      - self-hosted
      - macOS

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Test
      run: go test -v -o ${{env.NAME}}
 
    - name: Build
      run: $HOME/github/bin/build_go.sh

    - uses: actions/upload-artifact@v3
      with:
        name: ${{env.NAME}}_Executables
        path: _tmp
        retention-days: 7



