name: linux GO build

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:

  Build_and_AppCast_for_linux:
    runs-on: 
      - self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Linux GO Build
      run: $HOME/github/bin/build_go_linux.sh


