---
name: linux GO build

on:                          # yamllint disable-line rule:truthy
  schedule:
    - cron: '33 08 * * 6'
  workflow_dispatch:
  push:

jobs:

  Build_and_AppCast_for_linux:
    runs-on:
      - self-hosted

    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Linux GO Build
        run: $HOME/github/bin/build_go_linux.sh
